version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers

    working_directory: ~/repo/domod

    steps:
      - checkout

      - run:
          command: |
              if [[ -f package-lock.json ]]; then
                  rm package-lock.json
              fi

      - run: npm install

      - run: npm run build


